stages:
  - sast
  - dast

sast:
  stage: sast
  image:
    name: docker.io/owasp/glue
    entrypoint: [""]
  variables:
    GLUE_LOG_LEVEL: debug
  script:
    - glue -c .glue.yml
  artifacts:
    paths: [gl-sast-report.json]
    reports:
      sast: gl-sast-report.json

dast:
  stage: dast
  services:
    - name: owasp/zap2docker-stable
      alias: zap
  variables:
    DAST_WEBSITE: http://localhost:8000/docs
    ZAP_HEADLESS: true
    ZAP_API_KEY: zapapikey
    ZAP_AUTO_START: true
    ZAP_ADDITIONAL_COMMANDS: "python /zap/scripts/passive.py"
    DAST_FULL_SCAN_ENABLED: "true"
  script:
    - zap-cli quick-scan -P 8080 -r report.html -l Medium http://localhost:8000/docs
  artifacts:
    paths: [report.html]
    when: always

